name: Zip Root Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
     
  zip_files:
    runs-on: ubuntu-latest

    steps:    
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      # name: Build
      #  run: go build


      # Create a ZIP file containing all files in the root directory
      - name: Create ZIP file
        run: |
          make prep
          mkdir -p /tmp/shinsparxx
          rsync -a --exclude={'*.png','*.ico','*.ini','*.manifest','.gitignore','*.bat','*.syso','*.md','Makefile', '*.git', '*.github', 'config'} . /tmp/shinsparxx
          cd /tmp
          zip -r shinsparxx.zip shinsparxx
          mv shinsparxx.zip $GITHUB_WORKSPACE/shinsparxx.zip

      # Upload the ZIP file as an artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: shinsparxx
          path: shinsparxx.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "ShinSparxx UI"
          files: |
            shinsparxx.zip
