name: Zip Root Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a ZIP file containing all files in the root directory
      - name: Create ZIP file
        run: |
          mkdir -p /tmp/shinsparxx
          cp -r * /tmp/shinsparxx
          cd /tmp
          zip -r shinsparxx.zip shinsparxx
          mv shinsparxx.zip $GITHUB_WORKSPACE/shinsparxx.zip -x *.png

      # Upload the ZIP file as an artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: shinsparxx
          path: shinsparxx.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "ShinSparxx UI"
          files: |
            shinsparxx.zip
